projects:
  bonsai-growlab:
    desc: "Bonsai GrowLab Firmware"
    config:
      - CONFIG_BONSAI_FIRMWARE_SENSOR_BME280_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_BME280_SPI_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_SHT41_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_SOIL_ANALOG_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_LDR_ANALOG_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_DS18B20_SOIL_TEMPERATURE_ENABLE=y
      - CONFIG_BONSAI_FIRMWARE_SENSOR_DS18B20_OUTSIDE_TEMPERATURE_ENABLE=y
      - CONFIG_FREERTOS_USE_TRACE_FACILITY=y
  bonsai-zero-ar-1:
    desc: "Bonsai Zero Analog Relay 1"
  bonsai-zero-a-1:
    desc: "Bonsai Zero Analog 1"
