name: ESP32

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #
      # refs:
      #  - https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
      #  - https://github.com/actions/cache/blob/6849a6489940f00c2f30c0fb92c6274307ccb58a/tips-and-workarounds.md?plain=1#L57
      #  - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
      actions: write
    env:
      PROJECT_PATH: project
      IDF_PATH: esp-idf
      IDF_VERSION: v5.3.1
      CONFIGURATION_PATH_CCACHE: .env/ccache
      CONFIGURATION_PATH_BUILD_ALL: .env/esp32_configuration_build_all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_PATH }}
          submodules: recursive

      - name: Setup Prerequisites
        uses: ./project/ocs-esp-components/.github/actions/basic_env
        with:
          OCS_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}/ocs-esp-components
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}

      - name: Setup ESP-IDF
        uses: ./project/ocs-esp-components/.github/actions/esp32_env
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_VERSION: ${{ env.IDF_VERSION }}

      - name: Perform All Checks
        uses: ./project/ocs-esp-components/.github/actions/basic_checks
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          OCS_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}/ocs-esp-components

      - name: Prepare Configuration for Build All
        run: |
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_BME280_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_BME280_SPI_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_SHT41_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_YL69_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_LDR_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_DS18B20_SOIL_TEMPERATURE_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_DS18B20_OUTSIDE_TEMPERATURE_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
          echo "CONFIG_BONSAI_FIRMWARE_SENSOR_CAPACITIVE_V1_2_ENABLE=y" >> ${{ env.CONFIGURATION_PATH_BUILD_ALL }}
        shell: bash

      - name: Build All
        uses: ./project/ocs-esp-components/.github/actions/esp32_build
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}
          CONFIGURATION_PATH_PROJECT: ${{ env.CONFIGURATION_PATH_BUILD_ALL }}

      - name: Upload Artifacts
        uses: ./project/ocs-esp-components/.github/actions/esp32_upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          PROJECT_ID: artifacts-bonsai-build-all
